title: Celeritas: accelerated High Energy Physics Monte Carlo simulation
description: Redirect page for the Celeritas HEP project
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
include:
- _includes
- _layouts
- _sources
- _static
- _*.html
